// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/8/2026, 4:03:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/workspaces/Bli/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/plugins/**/*.{js,ts,mjs}","/workspaces/Bli/composables/**/*.{js,ts,mjs}","/workspaces/Bli/utils/**/*.{js,ts,mjs}","/workspaces/Bli/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/Bli/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;