// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2026, 11:01:22 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/runner/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/plugins/**/*.{js,ts,mjs}","/home/runner/workspace/composables/**/*.{js,ts,mjs}","/home/runner/workspace/utils/**/*.{js,ts,mjs}","/home/runner/workspace/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;